# action.yml
name: 'Build Therion maps'
description: 'Build maps from therion based project - fork of matteopic/therion-container'

inputs:
  thconfig:  # id of input
    description: 'thconfig file path'
    required: true
runs:
  using: 'docker'
  image: 'docker://speleobrad/therion:${{ env.RELEASE_VERSION }}'
  args:
    - ${{ inputs.thconfig }}

branding:
  icon: 'map'
  color: 'black'